#*******************************************************************************
#* Copyright (c) Johns Hopkins University. All rights reserved.
#* Licensed under the Apache License, Version 2.0.
#* See LICENSE.txt in the project root for license information.
#*******************************************************************************
name: nb_sciserver
channels:
  - anaconda-nb-extensions
dependencies:
  - notebook
