#*******************************************************************************
#* Copyright (c) Johns Hopkins University. All rights reserved.
#* Licensed under the Apache License, Version 2.0.
#* See LICENSE.txt in the project root for license information.
#*******************************************************************************
package:
  name: nb_sciserver
  version: 0.1.0

requirements:
  build:
    - notebook
    - python=3.6
  run:
    - notebook
    - python=3.6

test:
  imports:
    - nb_sciserver

source:
  path: ../

about:
  home: https://github.com/sciserver/nb_sciserver
  license: Apache-2.0
